In [ ]:
#Task1
N=int(input(("Enter array size: ")))
list=[0]*N

for i in range(0,N):
    num=int(input("Enter the numbers"))
    list[i]=num

newnum=int(input(("Enter new number ")))

newarray=[0]*(N+1)
for i in range(0,N):
    newarray[i]=list[i]

newarray[-1]=newnum
print(newarray)




In [ ]:
#Task2
N=int(input(("Enter array size: ")))
list=[0]*N
for i in range(0,N):
    num=int(input("Enter the numbers"))
    list[i]=num

print(list)

for i in range(0,N):
  if list[i]<0:
    list[i]=0
  else:
    list[i]=1

print(list)

Enter array size: 4
Enter the numbers4
Enter the numbers3
Enter the numbers-2
Enter the numbers1
[4, 3, -2, 1]
[1, 1, 0, 1]


In [2]:
#task3
import numpy as np

def reverseArray(arr1):

    start = 0
    end = len(arr1)-1

    while end > start:
        arr1[start],arr1[end] = arr1[end],arr1[start]
        start = start + 1
        end = end -1

    return arr1
arr1 = np.array([10, 12, 20, 5, 7])
print(arr1)
arr1 = reverseArray(arr1)
print(arr1)

[10 12 20  5  7]
[ 7  5 20 12 10]


In [ ]:
#Task 4
def printPairs(arr1, sum):
    pair= False
    for i in range(len(arr1)):
        for j in range(i + 1, len(arr1)):
            if arr1[i]+arr1[j]== sum:
                print(arr1[i],arr1[j])
                pair = True
    if pair==False:
        print("No Pair Found")
arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)



7 8
10 5


In [ ]:
#Task5
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
dot=0
for i in range(0,len(vec1)):
  dot+=vec1[i]*vec2[i]
print("Dot product:",dot)

if dot%2==0:
  print("After Swapping:")
  for i in range(0,len(vec1),2):
    vec1[i],vec2[i] = vec2[i],vec1[i]
  print(vec1)
  print(vec2)

else:
  for i in range(1,len(vec1),2):
    vec1[i],vec2[i] = vec2[i],vec1[i]
  print(vec1)
  print(vec2)





Dot product: 32
After Swapping:
[4 2 6]
[1 5 3]


In [ ]:
#Task6
N=int(input(("Enter array size: ")))
list=[0]*N

for i in range(0,N):
    num=int(input("Enter the numbers"))
    list[i]=num


def sort(list):
  for i in range(len(list)):
    min=i
    for j in range(i+1,len(list)):
      if list[j]<list[min]:
        min=j
    list[i], list[min]=list[min], list[i]
  print(list)
sort(list)

Enter array size: 6
Enter the numbers3
Enter the numbers2
Enter the numbers5
Enter the numbers7
Enter the numbers1
Enter the numbers8
[1, 2, 3, 5, 7, 8]


In [ ]:
#Task7
def flatten(arr):
    return arr.flatten()

arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = flatten(arr1)
print(arr2)

arr3 = np.array( [ [1, 4],[5, 6],[8, 9] ] )
arr4 = flatten(arr3)
print(arr4)

[1 2 3 3 4 5]
[1 4 5 6 8 9]


In [15]:
#Task8
def is_identity(matrix):
    n, m = matrix.shape
    if n!=m:
        return "Not an Identity Matrix"
    for i in range(0,n):
        for j in range(0,m):
            if i==j and matrix[i,j] == 0:
                return "Not an Identity Matrix"
            elif i!=j and matrix[i, j] == 1:
                return "Not an Identity Matrix"
    return "Identity Matrix"


A = np.array([ [1, 0, 0],
[0, 1, 0],
[0, 0, 1] ])

A=is_identity(A)
print(A)

A = np.array([ [1, 0, 0, 1],
[0, 1, 0, 0],
[1, 0, 1, 0],
[0, 1, 0, 1] ])
A=is_identity(A)
print(A)

Identity Matrix
Not an Identity Matrix


In [22]:
#Task9
A = np.array([ [1, 5, 12, 1],
[2, -4, 6, 7],
[3, 8, 5, 9],
[3, 5, 23, -6] ])

diagon1=0
diagon2=0
n,m = A.shape

for i in range(0,n):
  for j in range(0,m):
    if i==j:
      diagon1=diagon1+A[i,j]
    if i + j == n - 1:
      diagon2 += A[i, j]



result=abs(diagon1-diagon2)
print(result)

22


In [27]:
#Task10.1
A = np.array([[1, 2, 3],
 [4, 5, 6],
  [7, 8, 9]])

transpose= [[0 for i in range(n)] for j in range(m)]


n,m = A.shape

for i in range(0,n):
  for j in range(0,m):
    transpose[i][j]=A[j][i]
print(transpose)





[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [34]:
#Task10.2

result = np.dot(transpose, A)
print(result)


[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [45]:
#task11

def process_array(arr):
    avg=0
    m, n = arr.shape
    absolute = abs(m-n)
    remainder= absolute%m
    for i in arr[remainder]:
      avg+=i
    avg=avg/n
    avg=round(avg, 2)
    return arr*avg
A = np.array([[4, 1, 2], [9, 3, 7]])
result = process_array(A)
print(result)


[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]
